# Generated by Django 5.1.1 on 2024-09-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_widget'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='original_files/')),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='converted_files/')),
                ('original_filename', models.CharField(max_length=255)),
                ('original_file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('original_file_type', models.CharField(max_length=50)),
                ('converted_file_type', models.CharField(max_length=50)),
                ('conversion_type', models.CharField(choices=[('PDF', 'Converts to PDF'), ('JPG', 'Converts to  JPG'), ('PNG', 'Converts to PNG'), ('SVG', 'Converts to SVG')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
